set_property IOSTANDARD LVCMOS33 [get_ports {leds_0[0]}]
set_property PACKAGE_PIN N15 [get_ports {leds_0[0]}]
set_property PACKAGE_PIN G17 [get_ports {leds_0[5]}]
set_property PACKAGE_PIN L15 [get_ports {leds_0[3]}]
set_property PACKAGE_PIN M15 [get_ports {leds_0[1]}]
set_property PACKAGE_PIN L14 [get_ports {leds_0[4]}]
set_property PACKAGE_PIN G14 [get_ports {leds_0[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {leds_0[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {leds_0[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {leds_0[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {leds_0[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {leds_0[3]}]

set_property PACKAGE_PIN R16 [get_ports shield_i2c_scl_io]
set_property PACKAGE_PIN U12 [get_ports shield_i2c_sda_io]

set_property PACKAGE_PIN U13 [get_ports xclk_0]
set_property IOSTANDARD LVCMOS33 [get_ports xclk_0]
